import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Search from '@/app/components/Search';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-8 flex justify-center">
          <main className="max-w-5xl w-full space-y-6">
            <section className="space-y-2">
              <h1 className="text-4xl font-extrabold mt-16">Livefol.io</h1>
              <p>
                Forward test your Testfol.io strategy. Enter a link to a
                tactical allocation backtester.
              </p>
            </section>
            <Suspense fallback={<SearchSkeleton />}>
              <Search />
            </Suspense>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

function SearchSkeleton() {
  return (
    <div className="space-y-2 max-w-md">
      <div className="flex items-center gap-4">
        <div className="h-10 flex-1 rounded-xs bg-foreground/10 animate-pulse" />
        <div className="h-10 w-24 rounded-xs bg-foreground/10 animate-pulse" />
      </div>
      <div className="h-4 w-32 rounded-xs bg-foreground/10 animate-pulse" />
    </div>
  );
}
